version: '2'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /certs:/certs
    restart: always
  certs:
    build:
      context: ./certs
    container_name: certbot
    volumes_from:
      - nginx
    restart: always
    environment:
      - DOMAINS=abwesend.com www.abwesend.com
      - EMAIL=ich@abwesend.com
