version: '2'
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /certs:/certs
    restart: always
  certs:
    build:
      context: ./certs
    container_name: certbot
    volumes_from:
      - nginx
    restart: always
    environment:
      - DOMAINS=abwesend.com www.abwesend.com
      - EMAIL=ich@abwesend.com
  vpn:
    image: hwdsl2/ipsec-vpn-server
    container_name: vpn
    ports:
      - 500:500/udp
      - 4500:4500/udp
    volumes:
      - /lib/modules:/lib/modules:ro
    restart: always
    privileged: true
